LibraryWeb/Controllers/AuthorController.cs
using Common.Resources;
using Library.Domain.Dto;
using Library.Domain.Dto.Author;
using Library.Domain.Services.Interfaces;
using LibraryWeb.Handlers;
using Microsoft.AspNetCore.Mvc;

namespace LibraryWeb.Controllers
{
    [TypeFilter(typeof(CustomExceptionHandler))]
    public class AuthorController : Controller
    {
        #region Attribute
        private readonly IAuthorServices _authorServices;
        #endregion

        #region Builder
        public AuthorController(IAuthorServices authorServices)
        {
            _authorServices = authorServices;
        }
        #endregion

        #region Methods
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult GetAll()
        {
            List<AuthorDto> authors = _authorServices.GetAll();
            ResponseDto response = new ResponseDto()
            {
                IsSuccess = true,
                Message = string.Empty,
                Result = authors
            };

            return Ok(response);
        }

        [HttpPost]
        public async Task<IActionResult> Create(AddAuthorDto authorDto)
        {
            bool isCreated = await _authorServices.Create(authorDto);
            ResponseDto response = new ResponseDto()
            {
                IsSuccess = isCreated,
                Message = isCreated ? GeneralMessages.ItemInserted : GeneralMessages.ItemNoInserted,
                Result = isCreated
            };

            return Ok(response);
        }

        [HttpPut]
        public async Task<IActionResult> Update(AuthorDto updateAuthorDto)
        {
            bool isUpdated = await _authorServices.Update(updateAuthorDto);
            ResponseDto response = new ResponseDto()
            {
                IsSuccess = isUpdated,
                Message = isUpdated ? GeneralMessages.ItemUpdated : GeneralMessages.ItemNoUpdated,
                Result = isUpdated
            };

            return Ok(response);
        }

        [HttpDelete]
        public async Task<IActionResult> Delete(int id)
        {
            bool isDeleted = await _authorServices.Delete(id);
            ResponseDto response = new ResponseDto()
            {
                IsSuccess = isDeleted,
                Message = isDeleted ? GeneralMessages.ItemDeleted : GeneralMessages.ItemNoDeleted,
                Result = isDeleted
            };

            return Ok(response);
        }
        #endregion

    }
}

LibraryWeb/Controllers/BookController.cs
using Common.Resources;
using Library.Domain.Dto;
using Library.Domain.Dto.Book;
using Library.Domain.Services;
using Library.Domain.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace LibraryWeb.Controllers
{
    public class BookController : Controller
    {
        #region Attribute
        private readonly IBookServices _bookServices;
        #endregion

        #region Builder
        public BookController(IBookServices bookServices)
        {
            _bookServices = bookServices;
        }
        #endregion

        #region Methods
        [HttpGet]
        public IActionResult Index()
        {
            //IEnumerable<BookDto> books = await _bookServices.GetAll();
            return View();
        }

        //[HttpGet("{id}")]
        //public async Task<IActionResult> GetById(int id)
        //{
        //    BookDto book = await _bookServices.GetById(id);
        //    return Ok(book);
        //}

        [HttpGet]
        public IActionResult GetAll()
        {
            IEnumerable<BookDto> books = _bookServices.GetAll();
            ResponseDto response = new ResponseDto()
            {
                IsSuccess = true,
                Message = string.Empty,
                Result = books
            };

            return Ok(response);
        }

        [HttpPost]
        public async Task<IActionResult> Create(AddBookDto bookDto)
        {
            bool isCreated = await _bookServices.Create(bookDto);
            ResponseDto response = new ResponseDto()
            {
                IsSuccess = isCreated,
                Message = isCreated ? GeneralMessages.ItemInserted : GeneralMessages.ItemNoInserted,
                Result = isCreated
            };

            return Ok(response);
        }

        [HttpPut]
        public async Task<IActionResult> Update(UpdateBookDto bookDto)
        {
            bool isUpdated = await _bookServices.Update(bookDto);
            ResponseDto response = new ResponseDto()
            {
                IsSuccess = isUpdated,
                Message = isUpdated ? GeneralMessages.ItemUpdated : GeneralMessages.ItemNoUpdated,
                Result = isUpdated
            };

            return Ok(response);
        }

        [HttpDelete("{id}")]
        public async Task<IActionResult> Delete(int id)
        {
            bool isDeleted = await _bookServices.Delete(id);
            ResponseDto response = new ResponseDto()
            {
                IsSuccess = isDeleted,
                Message = isDeleted ? GeneralMessages.ItemDeleted : GeneralMessages.ItemNoDeleted,
                Result = isDeleted
            };

            return Ok(response);
        }
        #endregion
    }
}

LibraryWeb/Controllers/EditorialController.cs
using Common.Exceptions;
using Common.Resources;
using Library.Domain.Dto;
using Library.Domain.Dto.Editorial;
using Library.Domain.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace LibraryWeb.Controllers
{
    public class EditorialController : Controller
    {
        #region Attribute
        private readonly IEditorialServices _editorialServices;
        #endregion

        #region Builder
        public EditorialController(IEditorialServices editorialServices)
        {
            _editorialServices = editorialServices;
        }
        #endregion

        #region Methods
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult GetAll()
        {
            List<EditorialDto> editorials = _editorialServices.GetAll();
            ResponseDto response = new ResponseDto()
            {
                IsSuccess = true,
                Message = string.Empty,
                Result = editorials
            };

            return Ok(response);
        }

        [HttpPost]
        public async Task<IActionResult> Create(AddEditorialDto editorialDto)
        {
            bool isCreated = await _editorialServices.Create(editorialDto);
            ResponseDto response = new ResponseDto()
            {
                IsSuccess = isCreated,
                Message = isCreated ? GeneralMessages.ItemInserted : GeneralMessages.ItemNoInserted,
                Result = isCreated
            };

            return Ok(response);
        }

        [HttpPut]
        public async Task<IActionResult> Update(EditorialDto updateEditorialDto)
        {
            bool isUpdated = await _editorialServices.Update(updateEditorialDto);
            ResponseDto response = new ResponseDto()
            {
                IsSuccess = isUpdated,
                Message = isUpdated ? GeneralMessages.ItemUpdated : GeneralMessages.ItemNoUpdated,
                Result = isUpdated
            };

            return Ok(response);
        }

        [HttpDelete("{id}")]
        public async Task<IActionResult> Delete(int id)
        {
            bool isDeleted = await _editorialServices.Delete(id);
            ResponseDto response = new ResponseDto()
            {
                IsSuccess = isDeleted,
                Message = isDeleted ? GeneralMessages.ItemDeleted : GeneralMessages.ItemNoDeleted,
                Result = isDeleted
            };

            return Ok(response);
        } 
        #endregion
    }
}

LibraryWeb/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace LibraryWeb.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

       
    }
}

LibraryWeb/Views/Author/Index.cshtml
@model Library.Domain.Dto.Author.AuthorDto;
@{
    ViewData["Title"] = "Authors";
}
<div class="row">
    <div class="col-md-6">
        <h1>Listado de Autores</h1>
    </div>

    <div class="col-md-6">
        <button class="btn btn-primary float-end" onclick="modalNewAuthor()">
            <i class="fas fa-plus-square"></i>
            Nuevo Autor
        </button>
    </div>
</div>

<hr />

<div class="row">
    <div class="col-md-12">
        <table id="authorTable" class="table" style="width:100% !important">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Last Name</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody id="bodyAuthor">
            </tbody>
        </table>
    </div>

</div>


@*Modal Atuhor*@
<div class="modal fade" id="modalAuthor" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="1" role="dialog" aria-labelledby="modalProductLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="idTitleAuthor">Nuevo Autor</h5>
            </div>
            <div class="modal-body">
                <form id="formAuthor">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="row">
                        <div class="col-md-6 form-group">
                            <label class="col-form-label" asp-for="Name"></label>
                            <input asp-for="Name"
                                   placeholder="Nombre Autor"
                                   class="form-control" />
                            <span asp-validation-for="Name" class="text-danger"></span>
                        </div>
                        <div class="col-md-6 form-group">
                            <label class="col-form-label" asp-for="LastName"></label>
                            <input asp-for="LastName"
                                   placeholder="Apellido"
                                   class="form-control" />
                            <span asp-validation-for="LastName" class="text-danger"></span>
                        </div>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-bs-dismiss="modal" onclick="clearForm()">
                    <i class="fas fa-window-close"></i>
                    Cancelar
                </button>
                <button type="submit" class="btn btn-success" id="btnSave">
                    <i class="far fa-save"></i>
                    Guardar
                </button>
            </div>
        </div>
    </div>
</div>


@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }

    <script type="text/javascript" charset="utf-8">

        var listAuthor = [];
        let idAuthor = "";
        $(document).ready(function () {
            $("#btnSave").click(function () {
                $("formAuthor").submit(function (e) {
                    e.preventDefault();
                });

                saveAutor();
            });

            GetAllAuthor();
        });

        //Get All
        function GetAllAuthor() {
            modalProcessing(true, 'Cargando Autores');
            $.ajax({
                url: '@Url.Action("GetAll", "Author")',
                method: 'GET',
                dataType: "json",
                success: function (data) {
                    modalProcessing(false);
                    console.log(data);
                    if (data.isSuccess) {
                        listAuthor = data.result;
                        loadGrid(listAuthor);
                    } else {
                        Swal.fire(
                            'Opps!',
                            data.message,
                            'error');
                    }
                },
                error: function (xhr, textStatus, errorThrown) {
                    modalProcessing(false);
                    console.error(xhr, textStatus, errorThrown);
                    swaMessage(xhr.status, xhr.responseJSON.message);
                }
            });
        }

        function loadGrid(data) {
            //llenar registro
            if ($.fn.dataTable.isDataTable('#authorTable')) {
                var table = $('#authorTable').DataTable();
                table.destroy();
                loadGridAuthor(data);
                fillDataTable('authorTable');
            }
            else {
                loadGridAuthor(data);
                fillDataTable('authorTable');
            }
        }

        function loadGridAuthor(data) {
            $("#bodyAuthor").html("");

            for (var i = 0; i < data.length; i++) {
                var tr = `
                                            <tr>
                                                <th>`+ data[i].name + `</th>
                                                <th>`+ data[i].lastName + `</th>
                                            <td>
                                                <button  class="btn btn-warning" onclick="modalEditAuthor(`+ data[i].id + `)"><i class="fas fa-pen-nib iconSpace"></i> Editar</button>
                                                <button class="btn btn-danger" onclick="deleteAuthor(`+ data[i].id + `)"><i class="fas fa-trash-alt iconSpace"></i> Eliminar</button>
                                            </td>
                                            </tr>
                                        `;
                $("#bodyAuthor").append(tr);
            }
        }

        //Modal
        function modalNewAuthor() {
            clearForm();

            $('#idTitleAuthor').html('Nuevo Autor');
            const modal = new bootstrap.Modal('#modalAuthor', {
                keyboard: true
            });
            modal.show();
        }

        function modalEditAuthor(id) {
            clearForm();
            idAuthor = id;
            let author = listAuthor.find(x => x.id == idAuthor);
            console.log(author);
            $("#Name").val(author.name);
            $("#LastName").val(author.lastName);

            $('#idTitleAuthor').html('Editar Autor');
            const modal = new bootstrap.Modal('#modalAuthor', {
                keyboard: true
            });
            modal.show();
        }

        function clearForm() {
            $("#Name").val("");
            $("#LastName").val("");
            idAuthor = '';
        }
       
        //Save Autor
        function saveAutor() {
            if (!$("#formAuthor").valid()) {
                console.log("no es válido");
                return;
            }

            let params = {
                name: $("#Name").val(),
                lastName: $("#LastName").val(),
            };

            if (idAuthor == '')
                insertAuthor(params);
            else {
                params.id = idAuthor;
                updateAuthor(params);
            }
            console.log(params);

        }

        function insertAuthor(author) {
            modalProcessing(true);
            $.ajax({
                url: '@Url.Action("Create", "Author")',
                method: 'POST',
                data: author,
                dataType: "json",
                success: function (data) {
                    modalProcessing(false);
                    console.log(data);
                    if (data.isSuccess) {
                        $('#modalAuthor').modal('toggle');
                        GetAllAuthor();
                        toastMessage('success', data.message);

                    } else {
                        toastMessage('error', data.message);
                    }
                },
                error: function (xhr, textStatus, errorThrown) {
                    modalProcessing(false);
                    console.error(xhr, textStatus, errorThrown);
                    swaMessage(xhr.status, xhr.responseJSON.message);
                }
            });
        }

        function updateAuthor(author) {
            modalProcessing(true);
            $.ajax({
                url: '@Url.Action("Update", "Author")',
                method: 'PUT',
                data: author,
                dataType: "json",
                success: function (data) {
                    modalProcessing(false);
                    console.log(data);
                    if (data.isSuccess) {
                        $('#modalAuthor').modal('toggle');
                        GetAllAuthor();
                        toastMessage('success', data.message);

                    } else {
                        toastMessage('error', data.message);
                    }
                },
                error: function (xhr, textStatus, errorThrown) {
                    modalProcessing(false);
                    console.error(xhr, textStatus, errorThrown);
                    swaMessage(xhr.status, xhr.responseJSON.message);
                }
            });
        }

        function deleteAuthor(idAuthor) {
            Swal.fire({
                title: '¿Confirmar Eliminacion?',
                text: "No podrás revertir esto.!",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                cancelButtonText: 'Cancelar',
                confirmButtonText: 'Si, Eliminar!',
            }).then((result) => {
                if (result.isConfirmed) {
                    modalProcessing(true, 'Eliminando Autor');
                    $.ajax({
                        url: '@Url.Action("Delete", "Author")',
                        method: 'DELETE',
                        data: {
                            id: idAuthor,
                        },
                        dataType: "json",
                        success: function (data) {
                            modalProcessing(false);
                            if (data.isSuccess) {
                                toastMessage('success', data.message);
                                listAuthor = listAuthor.filter(x => x.id != idAuthor);
                                loadGrid(listAuthor);
                            } else {
                                toastMessage('error', data.message);
                            }
                        },
                        error: function (xhr, textStatus, errorThrown) {
                            modalProcessing(false);
                            console.error(xhr, textStatus, errorThrown);
                            swaMessage(xhr.status, xhr.responseJSON.message);
                        }
                    });
                }

            });

        }

    </script>
}

LibraryWeb/Views/Book/Index.cshtml
@model IEnumerable<Library.Domain.Dto.Book.BookDto>

<h1>Lista de Libros</h1>

<table id="booksTable" class="table table-bordered">
    <thead>
        <tr>
            <th>ID</th>
            <th>Título</th>
            <th>Sinopsis</th>
            <th>Número de Páginas</th>
            <th>URL de Imagen</th>
            <th>Autor</th>
            <th>Editorial</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var book in Model)
        {
            <tr>
                <td>@book.Id</td>
                <td>@book.Title</td>
                <td>@book.Sinopsis</td>
                <td>@book.N_Pages</td>
                <td>@book.UrlImage</td>
                <td>@book.AuthorName</td>
                <td>@book.EditorialName</td>
            </tr>
        }
    </tbody>
</table>

@section Scripts {
    <script>
        $(document).ready(function () {
            $('#booksTable').DataTable();
        });
    </script>
}

LibraryWeb/Views/Editorial/Index.cshtml
@model Library.Domain.Dto.Editorial.EditorialDto;

<h1>Lista de Editoriales</h1>

<table id="editorialsTable" class="table table-bordered">
    <thead>
        <tr>
            <th>ID</th>
            <th>Nombre</th>
            <th>Sede</th>
        </tr>
    </thead>
    <tbody id="bodyEditorial">
    </tbody>
</table>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }

    <script type="text/javascript" charset="utf-8">
        $(document).ready(function () {
           // $('#editorialsTable').DataTable();
           console.log('vista editorial');
        });
    </script>
}

LibraryWeb/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

LibraryWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LibraryWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/LibraryWeb.styles.css" asp-append-version="true" />

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css"
          integrity="sha512-1ycn6IcaQQ40/MKBW2W4Rhis/DbILU74C1vSrLJxCq57o941Ym01SwNsOMqvEBFlcgUa6xLiPY/NS5R+E6ztJQ=="
          crossorigin="anonymous"
          referrerpolicy="no-referrer" />

    @*data table*@
    <link rel="stylesheet" href="~/lib/DataTables/datatables.min.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">LibraryWeb</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Author" asp-action="Index">Author</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Editorial" asp-action="Index">Editorial</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

        <div class="modal fade" id="container-modal-procesando" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
        <div class="modal-dialog modal-sm modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-body" style="text-align:center;font-weight:bold">
                    <p id="mensaje-modal-procesando">Por favor espere</p>
                    <div align="center"><img style="width:100%" src="~/files/img/cargando_1.gif"></div>
                </div>
            </div>
        </div>
    </div>


    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - LibraryWeb - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11.3.6/dist/sweetalert2.all.min.js"></script>
    @*dataTable*@
    <script src="~/lib/DataTables/datatables.min.js"></script>



    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

<script>
    $(document).ready(function () {
        
    });

    function modalProcessing(desplegar, titulo) {
        if (desplegar) {
            if (titulo != undefined && titulo != null) {
                $("#mensaje-modal-procesando").html(titulo);
            }
            else {
                $("#mensaje-modal-procesando").html('Por favor espere');
            }
            const modalProcesando = new bootstrap.Modal('#container-modal-procesando', {
                keyboard: false
            });
            modalProcesando.show();
        } else {
            setTimeout(function () {
                $('.modal-backdrop').css("display", "none");

                const truck_modal = document.querySelector('#container-modal-procesando');
                const modal = bootstrap.Modal.getInstance(truck_modal);
                modal.hide();
                //closeModal('container-modal-procesando');
            }, 700);
            //$('.modal-backdrop').css("display", "none");
            // closeModal('container-modal-procesando');
        }
    }

    function toastMessage(type, message) {
        const Toast = Swal.mixin({
            toast: true,
            position: 'top-end',
            showConfirmButton: false,
            timer: 3000,
            timerProgressBar: true,
            didOpen: (toast) => {
                toast.addEventListener('mouseenter', Swal.stopTimer)
                toast.addEventListener('mouseleave', Swal.resumeTimer)
            }
        });

        Toast.fire({
            icon: type,
            title: message
        });
    }

    function swaMessage(statusCode, message) {
        console.log(statusCode)
        if (statusCode == 200) {
            Swal.fire('¡Bien!!', message, 'success');
        } else if (statusCode == 400) {
            Swal.fire('¡Alerta!', message, 'warning');
        } else {
            Swal.fire('¡Opps!', message, 'error');
        }
    }

</script>